Repository DIGOAI/chatbot-backend, pull requests merged in 2023-11, with the labels that each got.

#37 Feat client endpoints
  src/api/routes/__init__.py
  src/api/routes/client_routes.py
  src/api/routes/external_routes.py
  src/api/version.py
  src/common/cases/__init__.py
  src/common/cases/client_cases.py
Labels: enhancement

#38 Features socket API
  .DS_Store
  .env.example
  .gitignore
  Pipfile
  Pipfile.lock
  README.md
  docker-compose.yml
  docs/.DS_Store
  docs/schemas/db.pgerd
  docs/schemas/db.png
  main.py
  migrations/README
  src/api/cases/client_use_cases.py
  src/api/cases/ticket_use_cases.py
  src/api/routes/__init__.py
  src/api/routes/conversation_routes.py
  src/api/routes/email_routes.py
  src/api/routes/ticket_routes.py
  src/db/repositories/base_repository.py
  src/db/repositories/client_repository.py
  src/socket/__init__.py
  src/socket/routers/__init__.py
  src/socket/routers/chat/__init__.py
  src/socket/routers/chat/events.py
Labels: enhancement

#40 🚑 Update hashes and versions in Pipfile.lock.
  Pipfile.lock
Labels: bug

#41 ♻️ Refactor SocketIO mounting in main.py.
  main.py
  src/socket/__init__.py
  src/socket/routers/__init__.py
  src/socket/routers/chat/__init__.py
Labels: enhancement

#42 🚑 Remove redundant function call in main.py.
  main.py
Labels: bug, enhancement

#44 Feat cron jobs
  Pipfile
  Pipfile.lock
  migrations/script.py.mako
  migrations/versions/20231026_184933_seed_departments.py
  migrations/versions/20231107_142316_add_options_table.py
  migrations/versions/20231110_153912_merge_4c76fc92002e_and_ad4b7cb3f1eb.py
  src/api/__init__.py
  src/api/context.py
  src/api/routes/__init__.py
  src/api/routes/options_routes.py
  src/api/version.py
  src/common/cases/__init__.py
  src/common/cases/options_cases.py
  src/common/models/__init__.py
  src/common/models/options.py
  src/common/services/saragurosnet.py
  src/common/utils/__init__.py
  src/common/utils/patterns.py
  src/crons/__init__.py
  src/crons/data_reconciliation.py
  src/crons/schedule_thread.py
  src/crons/service_expiration.py
  src/db/models/__init__.py
  src/db/models/options.py
Labels: enhancement

#45 🚑 Fix cron jobs.
  src/api/version.py
  src/crons/data_reconciliation.py
  src/crons/schedule_thread.py
  src/crons/service_expiration.py
Labels: bug, enhancement

#46 ✨♻️🚑 Fixed critical error when fetch tickets data.
  docker-compose.yml
  src/api/cases/ticket_use_cases.py
  src/api/routes/ticket_routes.py
  src/api/utils/jwt_functions.py
  src/common/models/ticket.py
  src/db/models/client.py
  src/db/models/ticket.py
Labels: bug, enhancement

#47 🔖 Update api version to `0.100.0`.
  src/api/version.py
Labels: enhancement

#48 Feat-send-emails
  .env.example
  migrations/versions/20231113_141208_add_template_column_to_massive_.py
  src/api/routes/email_routes.py
  src/api/version.py
  src/common/cases/__init__.py
  src/common/cases/email_cases.py
  src/common/models/massive_template.py
  src/common/services/__init__.py
  src/common/services/smtp_service.py
  src/config/config.py
  src/db/models/massive_template.py
Labels: enhancement

#49 🐛 Fix `JWTBearer` dependency in `email_routes.py`
  src/api/routes/email_routes.py
  src/api/version.py
Labels: bug

#50 Feat-add-worker-ticket
  migrations/versions/20231113_161224_add_asigned_to_column_to_tickets_table.py
  src/api/cases/ticket_use_cases.py
  src/api/routes/ticket_routes.py
  src/common/models/__init__.py
  src/common/models/ticket.py
  src/db/models/ticket.py
  src/db/models/user.py
Labels: enhancement

#52 Add Ticket KPI endpoint
  src/api/cases/ticket_use_cases.py
  src/api/routes/ticket_routes.py
  src/api/version.py
Labels: enhancement

#53 added OCR utils & endpoint
  Pipfile
  Pipfile.lock
  src/api/cases/whatsapp_use_cases.py
  src/api/routes/__init__.py
  src/api/routes/ocr_routes.py
  src/api/routes/whatsapp_routes.py
  src/api/version.py
  src/common/models/ocr.py
  src/common/models/whatsapp.py
  src/ocr/__init__.py
  src/ocr/background.py
  src/ocr/images.py
Labels: enhancement

#51 ✨ [UPDATE] whatsapp api
  src/api/cases/whatsapp_use_cases.py
  src/api/routes/whatsapp_routes.py
  src/common/models/whatsapp.py
Labels: enhancement

#54 Refactor code structure and update dependencies
  Pipfile
  Pipfile.lock
  run.bash
  src/api/cases/__init__.py
  src/api/cases/auth_use_cases.py
  src/api/cases/client_use_cases.py
  src/api/middlewares/logger_handler.py
  src/api/routes/twilio_routes.py
  src/api/version.py
  src/chatbot/__init__.py
  src/chatbot/decisions_tree/__init__.py
  src/chatbot/decisions_tree/action.py
  src/chatbot/decisions_tree/decisions_tree.py
  src/chatbot/utils/__init__.py
  src/chatbot/utils/requester.py
  src/chatbot/utils/strings_utils.py
  src/chatbot/version.py
  src/common/cases/client_cases.py
  src/common/models/base.py
  src/common/models/client.py
  src/common/models/conversation.py
  src/common/models/massive_template.py
  src/common/models/message.py
  src/common/models/options.py
  src/common/models/responses.py
  src/common/models/ticket.py
  src/common/models/user.py
  src/common/services/__init__.py
  src/common/services/backend_service.py
  src/common/services/saragurosnet.py
  src/db/repositories/__init__.py
  src/db/repositories/client_repository.py
  src/saragurosnet/bussiness/__init__.py
  src/saragurosnet/bussiness/client_actions.py
  src/saragurosnet/bussiness/end_actions.py
  src/saragurosnet/bussiness/initial_actions.py
  src/saragurosnet/bussiness/no_client_actions.py
  src/saragurosnet/bussiness/preactions.py
  src/saragurosnet/bussiness/types/__init__.py
  src/saragurosnet/bussiness/utils.py
  src/saragurosnet/cases/__init__.py
  src/saragurosnet/cases/client_cases.py
  src/saragurosnet/types/__init__.py
  src/saragurosnet/types/department_types.py
  src/saragurosnet/types/media_types.py
  src/saragurosnet/types/message_types.py
  src/saragurosnet/types/option_types.py
  src/socket/__init__.py
Labels: enhancement

#55 ♻️ Refactor code and add OCR functionality.
  Pipfile
  Pipfile.lock
  src/api/cases/__init__.py
  src/api/cases/message_use_cases.py
  src/api/routes/auth_routes.py
  src/api/routes/massive_template_routes.py
  src/api/routes/ocr_routes.py
  src/api/routes/ticket_routes.py
  src/api/routes/whatsapp_routes.py
  src/api/version.py
  src/common/cases/__init__.py
  src/common/cases/template_cases.py
  src/common/cases/ticket_cases.py
  src/common/cases/user_cases.py
  src/common/cases/whatsapp_cases.py
  src/common/models/ocr.py
  src/db/repositories/__init__.py
  src/db/repositories/base_repository.py
  src/db/repositories/message_repository.py
  src/ocr/__init__.py
  src/ocr/background.py
  src/ocr/images.py
  src/ocr/types.py
Labels: documentation, enhancement

#56 ♻️🎨 Refactor OCR module and add ChatGPT integration.
  src/api/routes/ocr_routes.py
  src/common/cases/__init__.py
  src/common/cases/chatgpt_cases.py
  src/common/cases/ocr_cases.py
  src/common/services/chatgpt.py
  src/common/services/chatgpt/__init__.py
  src/common/services/chatgpt/promps.py
  src/common/services/chatgpt/types.py
  src/config/config.py
  src/ocr/__init__.py
  src/ocr/types.py
Labels: documentation, enhancement

#57 🔖 Update API version to `0.105.1`.
  src/api/version.py
  src/common/services/chatgpt/types.py
Labels: documentation

#58 ♻️ Refactor logger module and ci workflow.
  .github/workflows/migrate_db.yml
  src/api/middlewares/error_handler.py
  src/api/routes/twilio_routes.py
  src/chatbot/decisions_tree/action.py
  src/chatbot/decisions_tree/decisions_tree.py
  src/common/logger/__init__.py
  src/common/logger/logger.py
  src/common/logger/types.py
  src/common/services/saragurosnet.py
  src/config/config.py
  src/crons/__init__.py
  src/db/database.py
  src/saragurosnet/bussiness/initial_actions.py
  src/saragurosnet/bussiness/preactions.py
  src/saragurosnet/bussiness/utils.py
Labels: enhancement

#59 updated whatsapp routes
  src/api/cache/__init__.py
  src/api/routes/whatsapp_routes.py
  src/api/version.py
  src/common/cases/whatsapp_cases.py
  src/common/models/whatsapp.py
  src/common/utils/twilio.py
Labels: enhancement
